//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 05:47:04 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/test", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.mapsforge.preprocessing.poi.osmosis.jaxb;
