/*
 * Copyright 2010, 2011, 2012 mapsforge.org
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.11 at 03:25:14 PM MEZ 
//

package org.mapsforge.map.writer.automatization;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for sink complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sink">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="file" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="md5" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sink")
@XmlSeeAlso({ RoutinggraphWriter.class, WritePbf.class, MapfileWriter.class })
public abstract class Sink {

	/**
	 * The path to file. This is needed for every sink to store their execution data anywhere.
	 */
	@XmlAttribute(required = true)
	private String file;
	@XmlAttribute
	private Boolean md5;

	/**
	 * Gets the value of the file property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getFile() {
		return this.file;
	}

	/**
	 * Sets the value of the file property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setFile(String value) {
		this.file = value;
	}

	/**
	 * Gets the value of the md5 property.
	 * 
	 * @return possible object is {@link Boolean }
	 */
	public boolean isMd5() {
		if (this.md5 == null) {
			return false;
		}
		return this.md5;
	}

	/**
	 * Sets the value of the md5 property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 */
	public void setMd5(Boolean value) {
		this.md5 = value;
	}

	/**
	 * A abstract method that every sink must implemented to generate their explicit osmosis task call string.
	 * 
	 * @param md5List
	 *            list of files where a MD5 file should generated
	 * @param absoluteWorkingDirPath
	 *            the absolute path to the working directory
	 * @param absoluteOutputDirPath
	 *            the absolute path of the output directory
	 * @return the generated osmosis call
	 */
	public abstract String generate(List<String> md5List, String absoluteWorkingDirPath, String absoluteOutputDirPath);

}
