/*
 * Copyright 2010, 2011, 2012 mapsforge.org
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.11 at 03:25:14 PM MEZ 
//

package org.mapsforge.map.writer.automatization;

import java.io.File;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for pipeline complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pipeline">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://mapsforge.org/mapsforge-preprocessing-conf}source"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="output-dir" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="logging-level">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="FINE"/>
 *             &lt;enumeration value="FINER"/>
 *             &lt;enumeration value="FINEST"/>
 *             &lt;enumeration value="INFO"/>
 *             &lt;enumeration value="SEVERE"/>
 *             &lt;enumeration value="WARNING"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pipeline", propOrder = { "source" })
public class Pipeline {

	/**
	 * The source of the pipeline. The point where the execution started.
	 */
	@XmlElementRef(name = "source", namespace = "http://mapsforge.org/mapsforge-preprocessing-conf", type = JAXBElement.class)
	private JAXBElement<? extends Source> source;

	/**
	 * The name of the pipeline.
	 */
	@XmlAttribute(required = true)
	private String name;

	@XmlAttribute(name = "output-dir")
	private String outputDir;
	@XmlAttribute(name = "logging-level")
	private String loggingLevel;

	/**
	 * Gets the value of the source property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}{@link ReadPbf }{@code >} {@link JAXBElement }{@code <}
	 *         {@link Source }{@code >}
	 */
	public JAXBElement<? extends Source> getSource() {
		return this.source;
	}

	/**
	 * Sets the value of the source property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}{@link ReadPbf }{@code >} {@link JAXBElement }{@code <}
	 *            {@link Source }{@code >}
	 */
	public void setSource(JAXBElement<? extends Source> value) {
		this.source = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the outputDir property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getOutputDir() {
		return this.outputDir;
	}

	/**
	 * Sets the value of the outputDir property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setOutputDir(String value) {
		this.outputDir = value;
		System.out.println("set outputdir");

	}

	/**
	 * Gets the value of the loggingLevel property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getLoggingLevel() {
		return this.loggingLevel;
	}

	/**
	 * Sets the value of the loggingLevel property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setLoggingLevel(String value) {
		this.loggingLevel = value;
	}

	/**
	 * Generate the osmosis calls of the hole pipeline. Starting by the Source and traverse the tree downstairs. The
	 * path of the output directory would be actualized.
	 * 
	 * @param md5List
	 *            list of files where a MD5 file should generated
	 * @param absoluteWorkingDirPath
	 *            the absolute path to the working directory
	 * @param absoluteOutputDirPath
	 *            the absolute path of the output directory
	 * @return the generated osmosis call
	 */
	public String generate(List<String> md5List, String absoluteWorkingDirPath, String absoluteOutputDirPath) {

		if (this.outputDir != null) {
			// check if output directory of pipeline is absolute
			if (this.outputDir.startsWith(File.separator)) {
				// output directory of pipeline is absolute, so this would be used
				return this.source.getValue().generate(md5List, absoluteWorkingDirPath, this.outputDir);
			}
			// output directory is relative path, so it would be added to the given absolute
			// path of the configuration output directory
			return this.source.getValue().generate(md5List, absoluteWorkingDirPath,
					absoluteOutputDirPath + File.separator + this.outputDir);
		}

		// output directory of pipeline is not set, so wie use the default output directory of
		// the xml file
		return this.source.getValue().generate(md5List, absoluteWorkingDirPath, absoluteOutputDirPath);
	}

}
