/*
 * Copyright 2010, 2011, 2012 mapsforge.org
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.11 at 03:25:14 PM MEZ 
//

package org.mapsforge.map.writer.automatization;

import java.io.File;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for routinggraph-writer complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="routinggraph-writer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mapsforge.org/mapsforge-preprocessing-conf}sink">
 *      &lt;attribute name="way-types" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "routinggraph-writer")
public class RoutinggraphWriter extends Sink {

	@XmlAttribute(name = "way-types")
	private String wayTypes;

	/**
	 * Gets the value of the wayTypes property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getWayTypes() {
		return this.wayTypes;
	}

	/**
	 * Sets the value of the wayTypes property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setWayTypes(String value) {
		this.wayTypes = value;
	}

	@Override
	public String generate(List<String> md5List, String absoluteWorkingDirPath, String absoluteOutputDirPath) {

		final StringBuilder sb = new StringBuilder();

		// check output file
		File outputFile = null;
		outputFile = FileOperation.createWriteFile(absoluteOutputDirPath, getFile());

		if (outputFile == null) {
			throw new RuntimeException("An unexpected error occured. File is null.");
		}

		// check md5
		if (isMd5()) {
			md5List.add(outputFile.getAbsolutePath());
		}

		// generate osmosis call
		sb.append("--rgw").append(" ");
		sb.append("file=").append(outputFile.getAbsolutePath()).append(" ");
		if (this.wayTypes != null) {
			sb.append("way-types").append(this.wayTypes).append(" ");
		}

		return sb.toString();
	}

}
